sudo: required
dist: focal
services:
    - postgresql
language: node_js
node_js:
  - "18"
#  - "16"
#  - "14"
before_script:
  - psql -c 'create database pgboss'
  - psql -c 'create extension pgcrypto' -d pgboss
script:
  - npm run forcover
env:
  global:
  - PGPORT=5433
  - PGUSER=travis