dist: focal
language: node_js
node_js:
  - "18"
#  - "16"
#  - "14"
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
before_script:
  - psql -c 'create database pgboss'
  - psql -c 'create extension pgcrypto' -d pgboss
script:
  - npm run forcover
env:
  global:
  - PGPORT=5433
  - PGUSER=travis
  - PGHOST=localhost
  - PGPASSWORD=