sudo: required
dist: focal
addons:
    postgresql: "9.5"
services:
    - postgresql
language: node_js
node_js:
  - "18"
  - "16"
  - "14"
before_script:
  - psql -c 'create database pgboss' -U postgres
  - psql -c 'create extension pgcrypto' -d pgboss -U postgres
script:
  - npm run forcover
